apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-pinger-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-pinger
  template:
    metadata:
      labels:
        app: redis-pinger
    spec:
      containers:
      - name: redis-pinger
        image: koutiannvqing/redis-pinger:amd64
        env:
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
